server:
  port: 82
logging:
  level:
    com.wy: DEBUG
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:123456@eureka1:7001/eureka,http://admin:123456@eureka2:7002/eureka,http://admin:123456@eureka3:7003/eureka
feign:
  compression:
    request:
      enabled: true
      mime-type: #可以被压缩的类型
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048 #超过2048字节进行压缩
  hystrix:
    enabled: true
spring:
  zipkin:
    base-url: http://localhost:8601 #所在的数据提交到此服务中
    sender:
      type: web #提交的类型是web服务
  sleuth:
    sampler:
      probability: 1.0 #定义抽样比例，默认为0.1
  application:
    name: consumer-feign