server:
  port: 80
logging:
  level:
    com.wy: DEBUG
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:123456@eureka1:7001/eureka,http://admin:123456@eureka2:7002/eureka,http://admin:123456@eureka3:7003/eureka